### PR TITLE
Adds easy config for config-ui-x

### PR DESCRIPTION
**Pull request by donavanbecker**
@j796160836 please merge for easy config setup with [config-ui-x](https://github.com/oznu/homebridge-config-ui-x)

### CODE REVIEW

**Comment by j796160836** [comment]
Wow, nice support. Thanks for your contributions.

**Comment by donavanbecker** [comment]
@j796160836 no problem! thanks for merging

**Comment by donavanbecker** [comment]
@j796160836 you may wanna look into getting your plugin [verified](https://github.com/homebridge/verified) by the homeridge team.

**Comment by j796160836** [comment]
Cool things! But I haven't any Sengled devices now (has sold.)
May need your support.

**Comment by donavanbecker** [comment]
@j796160836 I don't have any sengled device either. Just trying to make it easier for others.

If you would like to transfer ownership for your plugin to the homebridge plugin organization, you are welcome too. and then we can wait for someone that would want to take over the plugin to make it better. See [unmaintained-plugins](https://github.com/homebridge/unmaintained-plugins).

**Pull request merged**
